import type { Metadata } from "next";
import {  Archivo } from "next/font/google"; 
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-provider";
import { Toaster } from "sonner";



const archivo = Archivo({
  variable: "--font-archivo", 
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${archivo.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors position="top-right" 
          />
        </ThemeProvider>
      </body>
    </html>
  );
}