import type { Metadata } from "next";
import {  Archivo } from "next/font/google"; 
import "./globals.css";
import "./styles/nprogress-custom.css";
import { ThemeProvider } from "@/components/Theme-provider";
import { Toaster } from "sonner";
import NProgressWrapper from "@/NprogressWrapper";
import { Suspense } from "react"; 



const archivo = Archivo({
  variable: "--font-archivo", 
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${archivo.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
               <Suspense fallback={null}>
               <NProgressWrapper>
          {children}
          <Toaster richColors position="top-right" 
          />
          </NProgressWrapper>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}